import Foundation

/// A lightweight mock translator for simulator testing.
/// Contains ~150 common English → Portuguese (Brazil) word pairs.
/// Used when Apple's Translation framework session is unavailable (simulator).
@MainActor
final class MockTranslator {
    static let shared = MockTranslator()

    private let dictionary: [String: String] = [
        // Greetings & Basics
        "hello": "olá",
        "hi": "oi",
        "goodbye": "adeus",
        "bye": "tchau",
        "please": "por favor",
        "thank you": "obrigado",
        "thanks": "obrigado",
        "yes": "sim",
        "no": "não",
        "good": "bom",
        "bad": "ruim",
        "okay": "ok",
        "welcome": "bem-vindo",

        // People & Family
        "man": "homem",
        "woman": "mulher",
        "boy": "menino",
        "girl": "menina",
        "child": "criança",
        "children": "crianças",
        "friend": "amigo",
        "family": "família",
        "mother": "mãe",
        "father": "pai",
        "brother": "irmão",
        "sister": "irmã",
        "son": "filho",
        "daughter": "filha",
        "husband": "marido",
        "wife": "esposa",
        "person": "pessoa",
        "people": "pessoas",

        // Body
        "head": "cabeça",
        "hand": "mão",
        "foot": "pé",
        "eye": "olho",
        "mouth": "boca",
        "heart": "coração",
        "body": "corpo",
        "arm": "braço",
        "leg": "perna",
        "face": "rosto",
        "hair": "cabelo",
        "nose": "nariz",
        "ear": "orelha",

        // Food & Drink
        "water": "água",
        "food": "comida",
        "bread": "pão",
        "rice": "arroz",
        "meat": "carne",
        "fish": "peixe",
        "fruit": "fruta",
        "apple": "maçã",
        "banana": "banana",
        "coffee": "café",
        "milk": "leite",
        "beer": "cerveja",
        "wine": "vinho",
        "juice": "suco",
        "sugar": "açúcar",
        "salt": "sal",
        "egg": "ovo",
        "cheese": "queijo",
        "chicken": "frango",
        "soup": "sopa",

        // Home & Objects
        "house": "casa",
        "door": "porta",
        "window": "janela",
        "table": "mesa",
        "chair": "cadeira",
        "bed": "cama",
        "book": "livro",
        "phone": "telefone",
        "car": "carro",
        "key": "chave",
        "light": "luz",
        "room": "quarto",
        "kitchen": "cozinha",
        "bathroom": "banheiro",
        "street": "rua",
        "city": "cidade",
        "country": "país",
        "school": "escola",
        "money": "dinheiro",
        "time": "tempo",
        "day": "dia",
        "night": "noite",
        "morning": "manhã",
        "today": "hoje",
        "tomorrow": "amanhã",
        "yesterday": "ontem",

        // Nature & Animals
        "dog": "cachorro",
        "cat": "gato",
        "bird": "pássaro",
        "tree": "árvore",
        "flower": "flor",
        "sun": "sol",
        "moon": "lua",
        "star": "estrela",
        "rain": "chuva",
        "sky": "céu",
        "sea": "mar",
        "river": "rio",
        "mountain": "montanha",
        "earth": "terra",
        "fire": "fogo",
        "wind": "vento",
        "snow": "neve",
        "horse": "cavalo",
        "cow": "vaca",
        "pig": "porco",

        // Colors
        "red": "vermelho",
        "blue": "azul",
        "green": "verde",
        "yellow": "amarelo",
        "black": "preto",
        "white": "branco",
        "orange": "laranja",
        "pink": "rosa",
        "brown": "marrom",
        "gray": "cinza",
        "purple": "roxo",

        // Numbers
        "one": "um",
        "two": "dois",
        "three": "três",
        "four": "quatro",
        "five": "cinco",
        "six": "seis",
        "seven": "sete",
        "eight": "oito",
        "nine": "nove",
        "ten": "dez",
        "hundred": "cem",
        "thousand": "mil",

        // Verbs (common)
        "eat": "comer",
        "drink": "beber",
        "sleep": "dormir",
        "walk": "andar",
        "run": "correr",
        "talk": "falar",
        "listen": "ouvir",
        "see": "ver",
        "look": "olhar",
        "read": "ler",
        "write": "escrever",
        "learn": "aprender",
        "teach": "ensinar",
        "love": "amar",
        "like": "gostar",
        "want": "querer",
        "need": "precisar",
        "have": "ter",
        "be": "ser",
        "go": "ir",
        "come": "vir",
        "give": "dar",
        "take": "pegar",
        "make": "fazer",
        "do": "fazer",
        "know": "saber",
        "think": "pensar",
        "feel": "sentir",
        "play": "brincar",
        "work": "trabalhar",
        "buy": "comprar",
        "sell": "vender",
        "open": "abrir",
        "close": "fechar",
        "help": "ajudar",

        // Adjectives
        "big": "grande",
        "small": "pequeno",
        "hot": "quente",
        "cold": "frio",
        "new": "novo",
        "old": "velho",
        "beautiful": "bonito",
        "happy": "feliz",
        "sad": "triste",
        "fast": "rápido",
        "slow": "lento",
        "easy": "fácil",
        "difficult": "difícil",
        "important": "importante",
        "different": "diferente",
        "same": "mesmo",
        "long": "longo",
        "short": "curto",
        "strong": "forte",
        "weak": "fraco",

        // Common phrases
        "how are you": "como vai você",
        "good morning": "bom dia",
        "good night": "boa noite",
        "see you": "até mais",
        "excuse me": "com licença",
        "i love you": "eu te amo",
        "i don't know": "eu não sei",
        "what is this": "o que é isso",
        "where is": "onde está",
        "my name is": "meu nome é",

        // Travel & Directions
        "airport": "aeroporto",
        "hotel": "hotel",
        "restaurant": "restaurante",
        "hospital": "hospital",
        "beach": "praia",
        "park": "parque",
        "church": "igreja",
        "market": "mercado",
        "bank": "banco",
        "pharmacy": "farmácia",
        "left": "esquerda",
        "right": "direita",
        "straight": "direito",
        "stop": "pare",
        "ticket": "passagem",
        "passport": "passaporte",
        "bag": "mala",
        "luggage": "bagagem",
        "map": "mapa",
        "taxi": "táxi",
        "bus": "ônibus",
        "train": "trem",
        "plane": "avião",
        "boat": "barco",
        "address": "endereço",
        "road": "estrada",
        "bridge": "ponte",
        "square": "praça",
        "museum": "museu",
        "library": "biblioteca",

        // Clothing
        "shirt": "camisa",
        "pants": "calça",
        "shoes": "sapatos",
        "hat": "chapéu",
        "dress": "vestido",
        "jacket": "jaqueta",
        "coat": "casaco",
        "socks": "meias",
        "gloves": "luvas",
        "scarf": "cachecol",
        "belt": "cinto",
        "tie": "gravata",
        "skirt": "saia",
        "shorts": "bermuda",
        "sweater": "suéter",
        "boots": "botas",
        "sandals": "sandálias",
        "uniform": "uniforme",
        "pajamas": "pijama",
        "pocket": "bolso",

        // Weather & Seasons
        "summer": "verão",
        "winter": "inverno",
        "spring": "primavera",
        "autumn": "outono",
        "cloud": "nuvem",
        "storm": "tempestade",
        "windy": "ventoso",
        "thunder": "trovão",
        "lightning": "raio",
        "fog": "neblina",
        "ice": "gelo",
        "heat": "calor",
        "warm": "morno",
        "cool": "fresco",
        "dry": "seco",
        "wet": "molhado",
        "humid": "úmido",
        "temperature": "temperatura",
        "forecast": "previsão",
        "rainbow": "arco-íris",

        // Emotions & Feelings
        "angry": "bravo",
        "tired": "cansado",
        "excited": "animado",
        "bored": "entediado",
        "nervous": "nervoso",
        "calm": "calmo",
        "proud": "orgulhoso",
        "ashamed": "envergonhado",
        "surprised": "surpreso",
        "confused": "confuso",
        "lonely": "solitário",
        "jealous": "ciumento",
        "grateful": "grato",
        "hopeful": "esperançoso",
        "worried": "preocupado",
        "relaxed": "relaxado",
        "comfortable": "confortável",
        "embarrassed": "envergonhado",
        "disappointed": "desapontado",
        "satisfied": "satisfeito",

        // Professions
        "doctor": "médico",
        "teacher": "professor",
        "student": "estudante",
        "driver": "motorista",
        "engineer": "engenheiro",
        "lawyer": "advogado",
        "nurse": "enfermeira",
        "chef": "chef de cozinha",
        "police": "policial",
        "firefighter": "bombeiro",
        "artist": "artista",
        "musician": "músico",
        "writer": "escritor",
        "farmer": "fazendeiro",
        "pilot": "piloto",
        "waiter": "garçom",
        "dentist": "dentista",
        "architect": "arquiteto",
        "photographer": "fotógrafo",
        "journalist": "jornalista",

        // More Verbs
        "dance": "dançar",
        "sing": "cantar",
        "cook": "cozinhar",
        "to clean": "limpar",
        "drive": "dirigir",
        "swim": "nadar",
        "fly": "voar",
        "jump": "pular",
        "sit": "sentar",
        "stand": "ficar de pé",
        "fall": "cair",
        "rise": "subir",
        "push": "empurrar",
        "pull": "puxar",
        "throw": "jogar",
        "catch": "pegar",
        "hold": "segurar",
        "carry": "carregar",
        "wait": "esperar",
        "call": "ligar",
        "answer": "responder",
        "ask": "perguntar",
        "explain": "explicar",
        "remember": "lembrar",
        "forget": "esquecer",
        "try": "tentar",
        "finish": "terminar",
        "begin": "começar",
        "choose": "escolher",
        "decide": "decidir",
        "promise": "prometer",
        "accept": "aceitar",
        "refuse": "recusar",
        "allow": "permitir",
        "forbid": "proibir",
        "invite": "convidar",
        "visit": "visitar",
        "travel": "viajar",
        "arrive": "chegar",
        "leave": "sair",
        "return": "voltar",
        "enter": "entrar",
        "exit": "sair",
        "pay": "pagar",
        "cost": "custar",
        "save": "economizar",
        "spend": "gastar",
        "count": "contar",
        "measure": "medir",
        "compare": "comparar",
        "change": "mudar",
        "grow": "crescer",
        "shrink": "encolher",
        "break": "quebrar",
        "fix": "consertar",
        "build": "construir",
        "destroy": "destruir",
        "create": "criar",
        "imagine": "imaginar",
        "dream": "sonhar",
        "laugh": "rir",
        "cry": "chorar",
        "smile": "sorrir",
        "shout": "gritar",
        "whisper": "sussurrar",

        // More Adjectives
        "clean": "limpo",
        "dirty": "sujo",
        "rich": "rico",
        "poor": "pobre",
        "cheap": "barato",
        "expensive": "caro",
        "free": "grátis",
        "busy": "ocupado",
        "quiet": "silencioso",
        "loud": "barulhento",
        "dark": "escuro",
        "bright": "brilhante",
        "soft": "macio",
        "hard": "duro",
        "smooth": "liso",
        "rough": "áspero",
        "sharp": "afiado",
        "blunt": "cego",
        "thick": "grosso",
        "thin": "fino",
        "wide": "largo",
        "narrow": "estreito",
        "deep": "profundo",
        "shallow": "raso",
        "heavy": "pesado",
        "light weight": "leve",
        "empty": "vazio",
        "full": "cheio",
        "round": "redondo",
        "square shape": "quadrado",
        "flat": "plano",
        "curved": "curvo",
        "straight line": "reto",
        "crooked": "torto",
        "modern": "moderno",
        "ancient": "antigo",
        "recent": "recente",
        "early": "cedo",
        "late": "tarde",
        "on time": "no horário",
        "correct": "correto",
        "wrong": "errado",
        "true": "verdadeiro",
        "false": "falso",
        "real": "real",
        "fake": "falso",
        "natural": "natural",
        "artificial": "artificial",
        "simple": "simples",
        "complex": "complexo",
        "basic": "básico",
        "advanced": "avançado",
        "perfect": "perfeito",
        "terrible": "terrível",
        "wonderful": "maravilhoso",
        "horrible": "horrível",
        "amazing": "incrível",
        "boring": "entediante",
        "interesting": "interessante",
        "funny": "engraçado",
        "serious": "sério",
        "strange": "estranho",
        "normal": "normal",
        "special": "especial",
        "common": "comum",
        "rare": "raro",
        "unique": "único",
        "famous": "famoso",
        "unknown": "desconhecido",
        "popular": "popular",
        "private": "privado",
        "public": "público",
        "safe": "seguro",
        "dangerous": "perigoso",

        // More Phrases
        "how much": "quanto custa",
        "i need help": "eu preciso de ajuda",
        "where is the bathroom": "onde é o banheiro",
        "i don't understand": "eu não entendo",
        "can you repeat": "pode repetir",
        "speak slowly": "fale devagar",
        "no problem": "sem problema",
        "of course": "claro",
        "maybe": "talvez",
        "right away": "agora mesmo",
        "later": "mais tarde",
        "right now": "agora mesmo",
        "a little": "um pouco",
        "a lot": "muito",
        "too much": "demais",
        "not enough": "não é suficiente",
        "just right": "na medida certa",
        "be careful": "tenha cuidado",
        "hurry up": "depressa",
        "take your time": "sem pressa",
        "what time is it": "que horas são",
        "i am lost": "estou perdido",
        "call the police": "chame a polícia",
        "i am sick": "estou doente",
        "where are you from": "de onde você é",
        "how old are you": "quantos anos você tem",
        "i like it": "eu gosto",
        "i don't like it": "eu não gosto",
        "it doesn't matter": "não importa",
        "cheers": "saúde",
        "congratulations": "parabéns",
        "happy birthday": "feliz aniversário",
        "merry christmas": "feliz natal",
        "happy new year": "feliz ano novo",
    ]

    private init() {}

    /// Translates a single English word to Portuguese.
    /// Returns the original text if no match is found.
    func translate(_ text: String) -> String {
        let trimmed = text.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return text }

        // Try exact match first.
        if let translated = dictionary[trimmed] {
            return translated
        }

        // Try case-insensitive match.
        for (key, value) in dictionary where key.lowercased() == trimmed {
            return value
        }

        // No match — return original text.
        return text
    }

    /// Returns whether the given text has a known translation.
    func hasTranslation(_ text: String) -> Bool {
        let trimmed = text.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
        return dictionary[trimmed] != nil
    }

    /// Returns the total number of word pairs in the dictionary.
    var wordCount: Int {
        dictionary.count
    }
}
